# Generated by Django 5.2.6 on 2025-10-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroSection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.AddField(
            model_name='hero',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
