# Generated by Django 5.2.6 on 2025-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='home_service',
            field=models.BooleanField(default=False),
        ),
    ]
