# Generated by Django 5.2.6 on 2025-10-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_home_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='home_service',
        ),
    ]
