# Generated by Django 5.2.6 on 2025-09-20 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('notifications', models.JSONField(default=dict)),
                ('barcode_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('seating_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('enable_no_parking_reports', models.BooleanField(default=True)),
                ('enable_sale_listing', models.BooleanField(default=False)),
                ('enable_rent_listing', models.BooleanField(default=False)),
                ('barcode_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_detail', to='barcodes.barcodeorder')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('warranty_till', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('enable_service_request', models.BooleanField(default=True)),
                ('enable_sale_listing', models.BooleanField(default=False)),
                ('enable_rent_listing', models.BooleanField(default=False)),
                ('barcode_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_detail', to='barcodes.barcodeorder')),
            ],
        ),
        migrations.CreateModel(
            name='HomeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enable_report_complaint', models.BooleanField(default=True)),
                ('enable_sale_listing', models.BooleanField(default=False)),
                ('enable_rent_listing', models.BooleanField(default=False)),
                ('barcode_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_detail', to='barcodes.barcodeorder')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barcode_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='barcodes.barcodeorder')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='barcodes.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('barcode_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_reports', to='barcodes.barcodeorder')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
