# Generated by Django 5.2.6 on 2025-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodeorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
