# Generated by Django 5.2.6 on 2025-09-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_machinery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinery',
            options={'verbose_name': 'Machineries', 'verbose_name_plural': 'Machineries'},
        ),
    ]
