# Generated by Django 5.2.6 on 2025-11-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_machinery_options_machinery_category_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='slot_interval',
            field=models.PositiveIntegerField(default=30, help_text='Slot duration in minutes'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Provider closing time (e.g. 06:00 PM)', null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='open_time',
            field=models.TimeField(blank=True, help_text='Provider opening time (e.g. 09:00 AM)', null=True),
        ),
    ]
