# Generated by Django 5.2.6 on 2025-11-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceprovider_slot_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.JSONField(default=list)),
                ('rating', models.FloatField(default=4.5)),
                ('distance', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_vendors', to='services.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('price_per_kg', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='grocery_items/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.groceryvendor')),
            ],
        ),
    ]
