# Generated by Django 5.2.6 on 2025-09-26 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sos',
            options={'ordering': ['status', '-timestamp'], 'verbose_name': 'SOS Service', 'verbose_name_plural': 'SOS Services'},
        ),
        migrations.AddField(
            model_name='sos',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sos',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled by User')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_sos', to=settings.AUTH_USER_MODEL),
        ),
    ]
