# Generated by Django 5.2.6 on 2025-11-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_alter_sos_options_sos_helper_sos_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPoolingVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('distance', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carpool_vendors/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Car Pooling Vendor',
                'verbose_name_plural': 'Car Pooling Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='SOS',
        ),
    ]
