# Generated by Django 5.2.6 on 2025-11-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_carpoolingvendor_delete_sos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpoolingvendor',
            options={},
        ),
    ]
